### ISSUE TITLE
Combine smash settings doesn't work?

### ISSUE THREAD

**Issue by Hazado** [matortheeternal/smash#124]
Using v0.2.2.2 Dev Build.

In the settings manager, I attempted to combine Bash.C.ImageSpace, Bash.C.Light, and Bash.C.Regions and nothing happened after highlighting all of them, right clicking them, then clicking combine settings. Used Cell Merge on the next screen. Click okay and nothing.

Same thing for Bash.Delev and Bash.Relev

**Comment by matortheeternal** [comment]
I'll check to see if this still happens in v0.3.1.

**Comment by matortheeternal** [comment]
Appears to be working in v1.0
