### ISSUE TITLE
VMAD on NPCS not being copied correctly

### ISSUE THREAD

**Issue by Hazado** [matortheeternal/smash#126]
Using the attached file (renamed to extension json) my VMAD records on NPCS copy strangely.

Attached screenshot to show you what I mean
![vmad](https://cloud.githubusercontent.com/assets/416114/13058627/3d75fd24-d3d9-11e5-8b91-d315dc9beb50.png)

[USLEEP Settings.txt](https://github.com/matortheeternal/smash/files/131338/USLEEP.Settings.txt)

**Comment by iaz3** [comment]
For me they just arent getting copied at all, half the time.

**Comment by matortheeternal** [comment]
I'm aware of issues with conflict resolution in VMADs.  You need to ignore them in your smash settings.

**Comment by matortheeternal** [comment]
May be fixed in v0.4 now that VMADs are being properly prototyped.
