### ISSUE TITLE
Remove non-masters from Patch

### ISSUE THREAD

**Issue by Dakraid** [matortheeternal/smash#129]
**What is the idea?**
The basic idea behind this feature would be to remove ESPs which haven't been added to the patch by comparing if the ESP is contained in the masters for the patch ESP.

This would remove unnecessary ESPs from the patch, allowing the user to remove them easier without having to reset the patch or cleaning unloaded ones from the patch.

**How would it work?**
The basic requirement would be that the patch has to been build once at least (no other way of knowing if an ESP is included within the patch or not).

For users there are a few options how to utilize this feature:
- The user can either enable the setting within the options
- The user  will receive a message dialog asking if he wants to remove untouched ESPs from the patch
- It could be provided as a context menu item when right-clicking on a patch

The process itself would check if an ESP is contained as master within the smashed patch ESP, if not the ESP gets removed from the patch.

**Comment by matortheeternal** [comment]
This was already built several weeks ago.
