### ISSUE TITLE
Armor not carrying over Body Template (BODT) record

### ISSUE THREAD

**Issue by RealAntithesis** [matortheeternal/smash#132]
I've been getting quite a few naked NPCs walking around after a smash (it's an all record smash, but preserving the existing tags). Looking into the smashed patch, none of the smashed Armor records have carried over the Body Template ('BODT'), which is blank. Changing this manually (by taking the last changed version - in my case, from Weapons & Armor Fixes Remade or Clothing & Clutter Fixes) fixes the naked NPCs issue.

**Comment by craigsumner** [comment]
This might be related to my report a while back here:
http://afkmods.iguanadons.net/index.php?/topic/4113-wip-mator-smash/page-8#entry158923

**Comment by matortheeternal** [comment]
this is most likely because there are multiple versions of the BODT subrecord (BOD2 and BODT).

**Comment by matortheeternal** [comment]
Probably related to #73

**Comment by matortheeternal** [comment]
Fixed in v0.4.
