### ISSUE TITLE
Changing a plugin's setting to "Skip" does not persist

### ISSUE THREAD

**Issue by Thallassa** [matortheeternal/smash#133]
When I change the "smash setting" of a plugin to "skip", it doesn't persist after closing the program. If I change it to a new setting, then it does persist.

**Comment by matortheeternal** [comment]
Will verify today.

**Comment by Freso** [comment]
I've had this/#148 happen as well. Sometimes I will close and reopen Smash to make sure it's actually using my settings, to avoid it displaying something different from what it's actually acting on.

**Comment by psolyca** [comment]
I had the same problem so I made a PR #159
