### ISSUE TITLE
Stops responding upon attempting to delete a patch

### ISSUE THREAD

**Issue by Thallassa** [matortheeternal/smash#134]
There's currently no way to remove a plugin from a patch other than deleting the patch and remaking it. 

However, when I attempt delete a patch from the UI, the entire program locks and must be force closed from task manager. 

(Deleting it from the .json file, or deleting the .json file entirely, works).

I haven't been able to do much troubleshooting on this issue. Please let me know if there's anything I can do to help.

**Comment by iaz3** [comment]
The issue seems to be that there is a confirmation dialog that pops up for this(im assuming, since i cant actually see it..), BUT, it's hidden BEHIND the window with no way to bring to the front. As a work around, pressing enter will accept it and delete the patch.

**Comment by matortheeternal** [comment]
I think this problem should be fixed in 0.3.1.
