### ISSUE TITLE
Does not recognize proper load order

### ISSUE THREAD

**Issue by ArtaiosGreybark** [matortheeternal/smash#137]
It seems that your program looks at time stamps when sorting the load order. I have a few instances where it will not load a plugin if the time stamp of the master esp/esm is equal to or later than the dependent esp/esm. iNeed and iNeed - Extended are an example. Both plugins have an identical time stamp according to Wrye Smash, but are correctly loaded by Skyrim, LOOT and NMM. Something to consider. Looking forward to further updates :smile:
 
This appears to be more complicated than I initially thought. I have the same problem with Enhanced Blood and its addon Reduced Wound size, which is set to one second later. So no idea why it is doing this. The load order in Mator Smash does not even resemble my load order. Strangely enough, saving iNeed - Extended does fix the problem with iNeed.
 
Also, when I create a patch it won't let me open it in Explorer (Windows 10). It says "Directories invalid". I cannot locate the file. Running it as admin.

**Comment by rshackleton** [comment]
Have the order issue too, it does not match the order shown in NMM, LOOT or WryeBash. This results in errors such as this:

![image](https://cloud.githubusercontent.com/assets/13448395/21598114/3f20fdf4-d14e-11e6-840c-69f7120f6112.png)

**Comment by anSTD** [comment]
Thank you for the "Redate Plugins" suggestion!  Mator Smash is still loading my plugins out of order, but at least it loads all of them now.

**Comment by matortheeternal** [comment]
This should be fixed in the latest version.
