### ISSUE TITLE
SNAM (description) character limit for CK

### ISSUE THREAD

**Issue by Kestatwala** [matortheeternal/smash#144]
Putting all of the patched mods in the plugin's description lead to overflow of the SNAM record. It is apparently expected by the CK to be less than 512:  

```
Chunk size 2931 too big in chunk SNAM_ID in form TES4_ID (FF000000).
Max size is 512, data truncated to "Smashed patch:
Unofficial Skyrim Special Edition Patch.esp
ClimatesOfTamriel.esm
Campfire.esm
Falskaar.esm
RSkyrimChildren.esm
Cutting Room Floor.esp
SMIM-SE-Merged-All.esp
Skyrim Flora Overhaul.esp
Verdant - A Skyrim Grass Plugin SSE Version.esp
Bring Out Your Dead.esp
SunDaytimeNorth_MM_default.esp
SunDaytimeSouth.esp
EnhancedLightsandFX.esp
Prometheus_No_snow_Under_the_roof.esp
Better Dynamic Snow.esp
Immersive Sounds - Compendium.esp
ClimatesOfTamriel-Falskaar.esp
Beards.esp
Improved".
```

The check is performed every tume the CK start, even without trying to load any plugin to work on it.

**Comment by Kestatwala** [comment]
Priority low obiously. The CK isn't trying to remove any data, it just complain it can't read it all. 
An advanced option to prevent to add the whole list in the SNAM for those of us who often start the CK while having a smashed patch sitting somewhere in their data folder would be great. Current workaround: deleting manually the SNAM through xEdit.

**Comment by matortheeternal** [comment]
I've been aware of this for awhile.  It's not really an issue.
