### ISSUE TITLE
Not reading Mod Organizer Load Order

### ISSUE THREAD

**Issue by PirateToshio** [matortheeternal/smash#145]
Whenever I try to run Mator Smash it fails to read the modlist.txt and shuffles my load order.

https://pastebin.com/nR8ZbC9M

I've gone into Settings -> Integrations and ticked "I'm Using Mod Organizer" and set up the paths but it's not working.

I'm using MO v2.0.8.3, which is a fork by LePresidente found [here.](https://github.com/LePresidente/modorganizer)

**Comment by matortheeternal** [comment]
1. Mator Smash does not ever read modlist.txt, modlist.txt doesn't have your load order, it has the mod install order.
2. Are you sure it's "shuffling" your load order and not just placing the DLCs in the wrong place?
3. It's MO's job to put loadorder.txt in a place where utilities can find them.  There is actually no reason for Mator Smash to have any MO integration.

**Comment by matortheeternal** [comment]
Are you using MO2 as an instance?  If so, you need to provide the instance name on the Integrations tab.

![](http://puu.sh/vR8ep.png)

**Comment by matortheeternal** [comment]
Closing this for now because I'm 90% certain it's user error.  If you need help reply here with additional information.
