### ISSUE TITLE
Changing plugin to Skip is not being recognized during patch

### ISSUE THREAD

**Issue by EssArrBee** [matortheeternal/smash#148]
First, set a list of mods to Bash.All. Returned to rerun the patch without two plugins and set both to Skip. After running the patcher neither mod was skipped in the resulting patch. Restarting Smash showed both plugins set back to Bash.All.

**Comment by matortheeternal** [comment]
Duplicate of #133 ?

**Comment by psolyca** [comment]
I have tried to look at this one but it seems that patch do not take plugin with Skip setting.
@EssArrBee could you provide more information ?
