### ISSUE TITLE
FO4: Smash.All duplicates conditions (CTDAs)

### ISSUE THREAD

**Issue by Freso** [matortheeternal/smash#151]
Using the Smash.All definition from https://github.com/matortheeternal/smash/commit/0c6533b71d678bac8d25f76a6481535c2ed09716 Smash will duplicate Condition records if the same conditions exist in two separate plugins.

Example:
Add "unofficial fallout 4 patch.esp" and "ValdacilsItemSorting-00-ValsPicks-DLCVersion-VanillaWeight.esp" to a smashed patch and smash them.

Expected outcome:
`PerkBobbleheadMedicine` should have only its `FULL` record changed.

Actual outcome:
`PerkBobbleheadMedicine` has `FULL` changed properly, but additionally a bunch of `CTDA`s now exist twice.

I don't think this has much gameplay impact, since the condition will be True or False even if it's checked twice, but it still adds clutter when browsing in FO4Edit (and maybe requires a bit more computation to check the conditions a second time, depending on how FO4 is coded).

**Comment by matortheeternal** [comment]
Should be fixed in v1.0
