### ISSUE TITLE
FO4: Official DLC misordered and deselected

### ISSUE THREAD

**Issue by WildfireDarkstar** [matortheeternal/smash#156]
When launching Mator Smash for Fallout 4 when _not_ using Mod Organizer 2, the six official DLC ESMs are deselected and placed incorrectly in the load order, after all other ESM files. The problem appears to be with the plugins.txt file %LocalAppData%\Fallout4. The DLCs are not listed there, and (I'm guessing?) Smash expects them to be. The problem can be "fixed" by manually adding the files in at the top of plugins.txt, but those lines are subsequently stripped by mod managers like Wrye Bash, which follow the "canonical" format that omits them from plugins.txt.

**Comment by matortheeternal** [comment]
I've seen this issue a lot, but this should not occur in the latest version.  What version are you using?

**Comment by matortheeternal** [comment]
Please try this build and let me know if it fixes the problem for you: http://puu.sh/xbRvN.zip

**Comment by WildfireDarkstar** [comment]
Previously, I was using this version:

> [03:00:25] (GENERAL) Status: ProgramVersion: 0.4.1.1

Which I understand is the most recent release. The executable files seem to match, at least. 

The newer build (version 0.5.0.0, going by the same status line in the log) _does_ fix the problem, though.

**Comment by matortheeternal** [comment]
OK, I'm going to try to push this build to the general public here in the next few days.  Glad it fixes the issue!
