### ISSUE TITLE
Skyrim: Bash.Sound (as well as the Smash.all) don't include Soul Gems

### ISSUE THREAD

**Issue by Doomathon** [matortheeternal/smash#157]
While I know of (and use) only one mod that adds pick up/put down sounds to soul gems, as a user I'd have expected that the settings would include them.

That being said, I can create custom smash settings that achieve what I'm after, so kudos for that.

**Comment by Doomathon** [comment]
Several months later, checked and this has been fixed (and this was a dupe anyway apparently), so closing.

**Comment by matortheeternal** [comment]
Thanks!
