### ISSUE TITLE
Missing an overriden record

### ISSUE THREAD

**Issue by goxaxa** [matortheeternal/smash#160]
I create a Mator Smash patch for my load order.
When I run xedit, and build references, the xedit message window shows these warnings:

<Warning: File [8D] MSmash.esp with Group GRUP Cell Children of SolitudeHalloftheDeadCatacombs "Solitude Catacombs" [CELL:000DD216] is missing an overriden record for SolitudeHalloftheDeadCatacombs "Solitude Catacombs" [CELL:000DD216]

<Warning: File [8D] MSmash.esp with Group GRUP Cell Children of WhiterunWarmaidens "Warmaiden's" [CELL:0001DB4E] is missing an overriden record for WhiterunWarmaidens "Warmaiden's" [CELL:0001DB4E]

<Warning: File [8D] MSmash.esp with Group GRUP Cell Children of WhiterunTempleofKynareth "Temple of Kynareth" [CELL:000165A7] is missing an overriden record for WhiterunTempleofKynareth "Temple of Kynareth" [CELL:000165A7]

I look at CELL:000DD216 in xedit and there is no MSmash.esp record for this cell,
but there are MSmash.esp records for child nodes of this cell.

Some of the child cells of CELL:000DD216 are
  0005E95E
  0006C059
  00086197

The mods relevant to these records are
  Skyrim.esm
  RelightingSkyrim_Legendary.esp
  Requiem.esp

I understand that Mator Smash at the end of its run deletes ITM and ITPO records.
It looks like sometimes it deletes a record which has child/leaf nodes.

**Comment by vensko** [comment]
Have the same issue.

**Comment by matortheeternal** [comment]
Problem appears to be fixed in v0.5 (which will be released later today, hopefully)
