### ISSUE TITLE
MS doesn't register current mod load order

### ISSUE THREAD

**Issue by Delgathar** [matortheeternal/smash#162]
This same problem existed with FO4Edit, until I updated it.  Mod load order on MS load is wrong.  It shows Fallout 4.esm and Unofficial Patch right below, but above all the DLCs.  Armor Keywords is also above the DLCs.  Loot and NMM show the correct load order.  After the update now FO4edit does too, but MS does not.

**Comment by matortheeternal** [comment]
Should be fixed in 6a4c9bd
