### ISSUE TITLE
Fallout 3 and New Vegas Smash.All settings missing

### ISSUE THREAD

**Issue by austen1000** [matortheeternal/smash#173]
In the 1.0.0 changelog, it is mentioned that Smash.All settings were added. However, looking at both the 1.0.0 and the 1.0.1 archive files, there is nothing for Fallout 3 or New Vegas in the settings folder. This is my first time posting an issue on GitHub.

**Comment by matortheeternal** [comment]
It appears something went wrong when packing the archive.  Here is an archive with Fallout 3 and Fallout NV Smash Settings packaged in it.  I'll make sure it's fixed in the next release as well.

[Mator Smash.zip](https://github.com/matortheeternal/smash/files/1975684/Mator.Smash.zip)
