### ISSUE TITLE
Smashing TREE CNAM Records: Entries Forwarded As Unknown Type (SkyrimIsWindy.esp)

### ISSUE THREAD

**Issue by lukemoore66** [matortheeternal/smash#176]
Attempting to smash SkyrimIsWindy.esp TREE CNAM values with SkyrimFloraFix.esp values. This happens with a custom Smash setting for CNAM values only, as well as the Smash.All setting. The actual values seem to smash, but they are forwarded as Unknown type.

**Comment by matortheeternal** [comment]
Can you attach a screenshot of the xEdit record view please?

**Comment by lukemoore66** [comment]
I was wrong with my description. The Unknown records are valid records. Smash seems to forward records from skyrim.esm, except for the first record, which changes from 0.40000 to 1.00000 for some reason. I have not included Skyrim.esm in the patch in Mator Smash, only SkyrimIsWindy.esp and FloraRespawnFix.esp. I don't know if this behavior even matters, as I'm not sure the Unknown records even get used anyway. Dare I say, it's likely a result of Smash skipping over Unknown records in some way when forwarding, I know that's what I would do.
![sseedit](https://user-images.githubusercontent.com/33060484/39802574-fc3092c6-53a0-11e8-9c70-be22ee0e8eec.PNG)

**Comment by matortheeternal** [comment]
Smash ignores "unknown" fields.  The first field getting changed is strange though, and may be a bug.  Might be worth verifying no Unknown field is set to process in Smash.All.

**Comment by matortheeternal** [comment]
Unknown fields are not set to be processed in Smash.All.  That may have been forwarded that way if you enabled Unknown in Smash.All.
