### ISSUE TITLE
Cannot close mator smash, not sure if patch is working

### ISSUE THREAD

**Issue by grahasc** [matortheeternal/smash#179]
Saving to C:\Program Files\Mator Smash\profiles\TES5\PluginInfo.json
Exception saving plugin errors Cannot create file "C:\Program Files\Mator Smash\profiles\TES5\PluginInfo.json". Access is denied
 
Dumping patches to JSON
 
Saving to C:\Program Files\Mator Smash\profiles\TES5\Patches.json

**Comment by grahasc** [comment]
I set the firewall to allow mayor smash, ran it as admistator, and changed the mator smash permissions in properties to allow all access. None of this worked. The same error showed up.
________________________________

**Comment by matortheeternal** [comment]
OK, Let's see what we can find out.

## Getting information
- Are you running an Antivirus?
- What version of Windows are you running?
- Does the path `C:\Program Files\Mator Smash\profiles\TES5\PluginInfo.json` exist?
- Have you run Merge Plugins successfully in the past?
- Are you using MO/MO2?

## Possible solutions

### Unblock executable
Right-click MatorSmash.exe, choose properties, and [click "Unblock" if it is present](http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2012/08/unblock.jpg).

### Take ownership
[Take ownership](http://www.itprotoday.com/management-mobility/taking-ownership-file-or-folder-command-line) of the Mator Smash folder

### Disable Windows Defender / add an exclusion
[Windows 10 - add exclusion to windows defender antivirus](https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus)

### Disable third party AV
This depends on your third party AV.  Do a google search if you're running one.

### Install smash somewhere else on disk
If all of these things don't work then you should try moving smash to a different location on disk.

**Comment by grahasc** [comment]
![screenshot 9](https://user-images.githubusercontent.com/39181860/39971531-fe2b5626-56b9-11e8-8d19-b99f49076bed.png)

**Comment by grahasc** [comment]
It seems like it can modify and save its patches anywhere else on my computer but as soon as it tries to save something into its own folder access is denied.

**Comment by grahasc** [comment]
Never mind all of that. It works...

**Comment by matortheeternal** [comment]
Glad you got it fixed.  :+1:
