### ISSUE TITLE
Previous Issue Unresolved

### ISSUE THREAD

**Issue by grahasc** [matortheeternal/smash#180]
This is pertaining to the issue I posted previously where mator smash says access denied and then will not close without task manager end task command. The following is what I have tried:

I set the firewall to allow mayor smash, ran it as admistator, and changed the mator smash permissions in properties to allow all access. None of this worked. The same error showed up.

**Comment by grahasc** [comment]
Sorry for any trouble.

**Comment by matortheeternal** [comment]
You should comment on the old issue, I'll reopen it.
