### ISSUE TITLE
Masters added for Skipped plugins

### ISSUE THREAD

**Issue by m0lz** [matortheeternal/smash#181]
When Smashing a NewPatch.esp, any plugins you have marked to be Skipped during the Smashing process, will still get included in the NewPatch.esp as a Master .. Is there any reason for this ?

**Comment by matortheeternal** [comment]
All plugins that have been assigned to the smashed patch will be added as masters to it.  If you don't want a plugin to be added as a master to the smashed patch, right-click it in the plugins view and choose "Remove from patch".
