### ISSUE TITLE
"BODT - Body Template" not propagated into Smash patch

### ISSUE THREAD

**Issue by goxaxa** [matortheeternal/smash#185]
The screen capture shows the problem.
https://www42.zippyshare.com/v/STPYnRaG/file.html
- The "BODT - Body Template" information is not copied into the patch.

But also, there should be no need for a conflict resolution patch, since KFR has Requiem.esp as a master and should override Requiem.esp

The Smash settings used are the same as in Smash.All.

**Comment by matortheeternal** [comment]
Duplicate of #166.
