### ISSUE TITLE
Access Violation (Either due to having 254 plugins OR due to mod 'Diverse Skyrim SSE')

### ISSUE THREAD

**Issue by ACMACMACM** [matortheeternal/smash#187]
I had 254 plugins I was trying to create a smash patch for.
Access Violation every time.
Disabled DIVERSE SKYRIM SSE and worked fine.
Either has to be number of plugins (thought 254 was the cutoff for Mator Smash), OR its the mod.

https://www.nexusmods.com/skyrimspecialedition/mods/7707?tab=files

**Comment by matortheeternal** [comment]
You wouldn't be able to run the game with 255 plugins anyways.  Try merging some stuff so you can reactivate Diverse Skyrim SSE.  If the problem still happens create a new issue.
