### ISSUE TITLE
[Feature Request] Worldspace XCAS - Acoustic Space

### ISSUE THREAD

**Issue by Mincol** [matortheeternal/smash#191]
Skyrim SE

I would like to ask to support XCAS and XCIM attributes for Worldspace.

I hope I just did not overlooked it. 

![image](https://user-images.githubusercontent.com/7746255/41502085-7825a586-71b2-11e8-939a-ec249a5c5b19.png)

**Comment by matortheeternal** [comment]
That's a CELL record.

![](http://puu.sh/AIcLk.png)
