### ISSUE TITLE
[FO4] The existance of a smashed patch causing CTD on main menu

### ISSUE THREAD

**Issue by Woffingshire** [matortheeternal/smash#194]
I created a smashed patch for Fallout 4 but whenever it is enabled the game CDTs before the main menu has even opened. There is nothing wrong with the patch its self, but the patch simply being enabled is what is causing the crash.
I tested this through deleting each catagory, QST, LVLI and so on and relaunching the game to see if the crash was fixed. It was not, until in the end the patch was empty. It was just an esp with nothing in it, but the game still crashed upon launch. It was only when I disabled the empty patch that the crashing stopped instantly.

**Comment by matortheeternal** [comment]
It sounds like you built the smashed patch with a plugin enabled that you then didn't have enabled when you ran the game.  Check the smash patch's masters against the plugins you have enabled in your load order.  If you use Mod Organizer it will tell you what masters are missing.
