### ISSUE TITLE
Mator Smash Causes MO2 to Crash When Patch Is Created

### ISSUE THREAD

**Issue by hamletsdead** [matortheeternal/smash#195]
Mator Smash works fantastically well, thanks Mator. The only (trivial) issue I have is that when the patch is created MO2 freezes then shuts down. When I restart, the Smashed Patch is in the Overwrite folder, so it's not a big deal, but presumably this is not a planned event. 

FYI, it does this every single time a new patch is created.

**Comment by matortheeternal** [comment]
That sounds like an issue with MO2.
