### ISSUE TITLE
Record lost when multiple plugins in place

### ISSUE THREAD

**Issue by Mincol** [matortheeternal/smash#203]
If I try to create patch using just two plugins, the XCAS record is smashed correctly.
![image](https://user-images.githubusercontent.com/7746255/42040224-736fb126-7aef-11e8-8cb9-565139902b52.png)
But If I run smash on my full load order, it seems to loose that record.
![image](https://user-images.githubusercontent.com/7746255/42040300-95cd8040-7aef-11e8-88e8-73a90e780881.png)
What can cause this? Is this bug? Setting should be same for both smashed patches...

**Comment by matortheeternal** [comment]
does Immersive Citizens - ELE patch.esp have SoundsOfSkyrimComplete.esp as a master?  I don't think so.  If not then I'll test on my end and see what I can discover.

**Comment by Mincol** [comment]
No. Masters of  Immersive Citizens - ELE patch.esp are Immersive Citizens - AI Overhaul.esp and ELE_SSE.esp

SoundsIfSkyrimComplete.esp has settings Bash.Sound-My while ELE_SSE.esp has BashC..Light-My 
[Skyrim.zip](https://github.com/matortheeternal/smash/files/2146516/Skyrim.zip)

It is something else. If I have only SoundsIfSkyrimComplete.esp + ELE_SSE.esp it works OK.
If I have  SoundsIfSkyrimComplete.esp + ELE_SSE.esp +Immersive Citizens - ELE patch.esp it still works OK. (Immersive Citizens - ELE patch.esp and Immersive Citizens - AI Overhaul.esp have Smash.All)

Another try with one patch only and it worked...

Aaaand finally I can reproduce it,

If I remove Immersive Citizens - ELE patch.esp but keep all my other plugins then smashed patch does not contains that record...

Still need to minimise "test case". It is reproducible on my end at least. Ideas?

**Comment by Mincol** [comment]
This works:
![image](https://user-images.githubusercontent.com/7746255/42057598-285e56cc-7b1e-11e8-8fa3-40e859a8e4ea.png)
This not:
![image](https://user-images.githubusercontent.com/7746255/42057635-4b0d07d6-7b1e-11e8-81de-03deb79fa115.png)
Missing record:
![image](https://user-images.githubusercontent.com/7746255/42057821-ccc77f72-7b1e-11e8-95b7-1e7ab56d19da.png)

I am unable to minimize it...

**Comment by Mincol** [comment]
I did not had time to play nor program. Now I had time, so I updated my mods. That was mistake. I cannot reproduce this anymore.
