### ISSUE TITLE
Non-"Smash." settings are instantly reverted when starting to build the patch

### ISSUE THREAD

**Issue by cmeeren** [matortheeternal/smash#205]
I changed a plugin from `Smash.All` to a custom `Bash.<something>` tag, but once I started building the patch it was reverted to `Smash.All`. That also happened when changing to a custom ungrouped setting. If I name my setting `Smash.<something>`, the setting sticks correctly and is applied.

**Comment by cmeeren** [comment]
Note that this happens only when clicking the green arrow, not the hammer.

**Comment by Ufeldraku** [comment]
The green arrow applies smash.all to all plugins except Bethesda's ones.

For your settings to remain, you need to use the hammer.

**Comment by cmeeren** [comment]
Thanks, nevermind then.

(Is there any place I could have read that? Is there any official up-to-date documentation for Mator Smash?)

**Comment by Ufeldraku** [comment]
@cmeeren  Yep, it's on the official mator smash nexus page.

It was a feature.
