### ISSUE TITLE
Smashed patch being deleted by wyrebash

### ISSUE THREAD

**Issue by GrimSovereign** [matortheeternal/smash#209]
Every time I make a smashed patch for Skyrim SE and I go to load up wyrebash to check on my load order afterwards to make sure nothing was moved around it says "missing plugins were deleted". The smashed patch is in my data folder before opening wyrebash so I don't understand how or why it's being deleted.

**Comment by matortheeternal** [comment]
This sounds like an issue with Wrye Bash, not Smash?

**Comment by GrimSovereign** [comment]
I figured it out. Apparently when not ran in admin mode it won't save so every time i exited the smash app the patch was denied access to my data folder.

**Comment by matortheeternal** [comment]
ok.
