### ISSUE TITLE
Accented characters replaced by symbols

### ISSUE THREAD

**Issue by Guekka** [matortheeternal/smash#212]
Hi, I'm French, and on the website La Confrérie des Traducteurs, we always recommend your program. But there's a problem related to accented characters. When we create a smashed patch, accented characters are replaced by symbols like " §? . {# "
Maybe a problem related to UTF-8 support (#169) ?
Thanks.

**Comment by matortheeternal** [comment]
Yes, this is due to the addition of UTF-8 support.  I forced the program to use UTF-8 encoding by default when it should be using either UTF-8 or CP-1252 depending on the language used.
