### ISSUE TITLE
Force doesn't work?

### ISSUE THREAD

**Issue by cmeeren** [matortheeternal/smash#217]
In this collection of mods, the SNAM value is not forwarded. `Immersive Sounds - Compendium.esp` uses a modification of `Smash.All` where the `SNAM` is forced, and all other plugins shown here use `Smash.All`. I'd expect the Smashed Patch to contain the SNAM from ISC, but it doesn't. What's happening here?

![image](https://user-images.githubusercontent.com/7766733/42900877-51b88e0a-8aca-11e8-89dc-fa6ab11a5f7c.png)

**Comment by cmeeren** [comment]
Do you mean at the top level? E.g. it works at `ARMO` but not `ARMO/DESC`? If so, then the option should be disabled for all levels where it does not work.

Could support for forcing sub-records be implemented? It would make Mator Smash much more flexible with regards to custom rules.

**Comment by matortheeternal** [comment]
> Do you mean at the top level? E.g. it works at `ARMO` but not `ARMO/DESC`?

Yes, precisely.

> If so, then the option should be disabled for all levels where it does not work.

Already done, see #193

> Could support for forcing sub-records be implemented?

Unfortunately it's not possible without making massive changes to the algorithm which aren't planned for this application.  It will be possible in zSmash (which will be developed at a future point in time).
