### ISSUE TITLE
Construction Kit

### ISSUE THREAD

**Issue by Thenryb** [matortheeternal/smash#227]
I created a smashed patch for Skyrim SE. When I open the construction kit, I get a warning that the "chunk size" is too large. I have just cleared the warning and moved on to load whatever plug-in I want to look at, but am still curious whether this is something to be concerned about. This may have been discussed before, but my cursory search before posting did not reveal any such discussion.

**Comment by matortheeternal** [comment]
I'm not sure about this error, but I wouldn't recommend loading a smashed patch in the CK under any circumstances.  Use SSEEdit instead.

**Comment by Thenryb** [comment]
The warning I am talking about occurs when you activate the CK when you have a smashed patch in your load order and before you even select which plug in to load.

**Comment by matortheeternal** [comment]
> The warning I am talking about occurs when you activate the CK when you have a smashed patch in your load order and before you even select which plug in to load.

How big is your load order prior to generating the smashed patch?  Perhaps you're too close to the 255 plugin limit?  The only thing the CK should parse prior to loading plugins is file headers, so the number of masters or the SNAM - Description field are the most likely culprits.  The latter is a known thing the CK complains about - it wants the description to be <255 characters, but the game doesn't care how long it is.

**Comment by Thenryb** [comment]
I have 151 active plugins and 171 total. Without Smashed Patch. esp that number is reduced by one. I do not get that warning if I uninstall the Smashed Patch. Here is the exact wording of the warning:
"Chunk size 3530 too big in chunk SNAM_ID in form TES4_ID (FF000000).
Max size is 512, data truncated to "Smashed patch:"
This is total greek to me.

**Comment by matortheeternal** [comment]
This is the description exceeding the limit.  It sounds like the limit is 512 characters (not 255, as I thought previously).  The Smashed patch puts every plugin's filename into the description, so it will regularly end up "too long".  But the game doesn't care how long the description is, only the CK complains.  What's happening here is the CK is truncating the description.  There's nothing to worry about here.
