### ISSUE TITLE
Support MO2 profile selection or detection

### ISSUE THREAD

**Issue by jarrard** [matortheeternal/smash#239]
Currently smash assumes that your running profile default, there is no option to change to different mo2 profile directories so it just always goes for profile/default/plugins.txt  ...  

Me nice if there was a feature to choose a different mo2 profile (or just autodetect).

Thanks, nice app btw.

**Comment by matortheeternal** [comment]
Smash doesn't have any need to integrate with MO2.  It's MO2's responsibility to tell smash what load order to use (Smash just looks in the same directory where the game looks).  As long as you start smash through MO2 everything should work fine.  :)

**Comment by jarrard** [comment]
Smash actually looks in the MO2 directory and assumes the profile being used is default. Even says so in the smash logs, MO2 can't tell Smash what to do if smash assumes it.

**Comment by matortheeternal** [comment]
If you see smash looking in an MO2 directory then you're using an old version.  there is absolutely nothing in recent versions of Mator Smash which interacts with MO2.
