### ISSUE TITLE
Loaded ESP's excluded from patch creation still influence patch contents

### ISSUE THREAD

**Issue by MagielBruntink** [matortheeternal/smash#27]
For instance: If you load up Mator Smash with a TES5Edit or Bashed Patch activated, these EPS's will influence patches you create in Smash, even if you exclude them from the patch and/or pick the "Skip" setting. Create a Merged Patch in TES5Edit for instance with some CONT records and load that into Smash. Then create a patch setting for CONT records and create a patch while excluding TES5Edit. Smash will then not include CONT records that TES5Edit already merged.

**Comment by MagielBruntink** [comment]
This appears to happen only if the TES5Edit patch in the above example is higher in the load order than the generated Smashed Patch.

**Comment by MagielBruntink** [comment]
Scratch that last comment. Also, if you load ASIS and exclude it from your Smash patches, the changes it makes (to NPC's for instance), still end up in the Smashed patches.

**Comment by matortheeternal** [comment]
This was fixed with #21
