### ISSUE TITLE
Store smash settings in game-specific directories

### ISSUE THREAD

**Issue by matortheeternal** [matortheeternal/smash#33]
`.\settings\<Game>\<SettingName>.json`

This will allow us to load only smash settings associated with a particular game.

**Comment by Dakraid** [comment]
What do you exactly mean with "Smash Version"? As long as the algorithm stays the same or similar, versioning shouldn't matter for the attributes, or am I mistaken?

**Comment by matortheeternal** [comment]
The smash version is mainly relevant right now while the algorithm/gui for making the smash setting is changing.

**Comment by matortheeternal** [comment]
But it's quickly becoming irrelevant so we can not do that part.

**Comment by matortheeternal** [comment]
Jesus GitHub, couldn't combine all those name changes into a single item, huh?  >_>'
