### ISSUE TITLE
Loaded ESP's excluded from patch creation influence patch contents

### ISSUE THREAD

**Issue by InfamousNate** [matortheeternal/smash#40]
I'm having the same problem as #27 that was supposedly fixed with #21.  I'll try to provide as much detail as possible:

My load order/plugins loaded in tes5edit: http://pastebin.com/w8WDgkrE#

Screenshot of the issue: http://imgur.com/MR6S0r2

The above list of plugins was loaded into Mator Smash and a patch was created using the SKIP setting for all plugins except for: 
-Potions.esp (Custom setting using ALCH tree with model branch only)
-SSfS-ALCH.esp (Custom setting using ALCH tree with Full Name branch only)
-SSfS-FOOD.esp (Custom setting using ALCH tree with Full Name branch only)

These 3 plugins were selected to be smashed into a "test Patch.esp".  After successful creation, the new esp was loaded into Tes5Edit with my full load order and the above screenshot was taken after I noticed 2 effects.  Both listed effects within the test patch.esp are the same exact EFID - Effect Data; AlchFortifyAlteration "Fortify Alteration" [MGEF:0003EB24] with the only difference being the Magnitude.

The issue is consistent with 218/219 ingestible records within the Mator Smash created patch.  The only exception being Sleeping Tree Sap.  The only override in this record was Model (from potions.esp)

**Comment by matortheeternal** [comment]
@InfamousNate Do you still have the smash setting you used for this?  Because based on what I see I'm pretty sure your smash setting did not skip the Effects element.  There's no way for the code to merge arrays like that unless the Effects element isn't being skipped.

**Comment by InfamousNate** [comment]
I haven't touched Smash since I reported this issue due to time, so these setting have not changed since I last ran a patch.  Here are the setting I used: http://imgur.com/a/cc9YB. As stated above I loaded my entire load order into MS but only selected 3 esp's to merge using these two settings only.

**Comment by matortheeternal** [comment]
Verified the issue.  Will have a developer build soon.

**Comment by matortheeternal** [comment]
Developer build: [v0.0.7.35](http://puu.sh/mhhoK.zip)
