### ISSUE TITLE
Force Value

### ISSUE THREAD

**Issue by matortheeternal** [matortheeternal/smash#89]
Will allow you to force Smash to use an element from a specific mod ignoring changes from other mods regardless of load order.

**Comment by goxaxa** [comment]
I've just started using Mator Smash, and this is a feature I was hoping or expecting to find.

There are possibly two optional ways to define this new feature.
1. Force element to be the winning value, for all plugins up to this one in the load order, but let later plugins overwrite it.
2. Force element to be the winning value, for all plugins, regardless of load order.

For a mod like Requiem, option #1 would be useful to force Requiem's plugin elements to win, but to also let later plugins (Requiem patches) override Requiem's values.

**Comment by matortheeternal** [comment]
So for 1 you would only let a plugin overwrite the value if it had the "forced" plugin as a master?

**Comment by goxaxa** [comment]
Yes.
Using ingredients as an example. Requiem changes the value and effects for many ingredients. So it would be useful to be able to say to Mator Smash,
"Force the ingredient to take the value from Requiem.esp, ignoring Skyrim.esm and all plugins loaded before Requiem.esp. But allow Requiem patches (which have Requiem.esp as a master) to patch the Requiem ingredient records".

**Comment by matortheeternal** [comment]
Implemented for records.  Still need to implement for individual elements/fields.
